# Generated by Django 5.0.6 on 2024-05-16 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('desc', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('desc', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('desc', models.TextField(blank=True, default='')),
                ('date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlansTrainigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainapp.plans')),
                ('trainings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainapp.trainings')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingsExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(blank=True, null=True)),
                ('repeat', models.IntegerField(blank=True, null=True)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainapp.exercises')),
                ('trainings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainapp.trainings')),
            ],
        ),
    ]
