# Generated by Django 5.0.6 on 2024-05-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainigs_exercises',
            name='repeat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainigs_exercises',
            name='series',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
